version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    command: mongod --quiet --logpath /dev/null
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  server-service:
    build: server
    container_name: server
    environment:
      - PORT=8080
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost # -- didn't think about this yet
      - JWT_SECRET=update_your_JWT_secret
      - MONGO_URI=mongodb://mongo:27017/mern_ecommerce
      - NODE_ENV=production
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    networks:
      - app-network

  client:
    build: client
    container_name: client
    ports:
      - '3000:3000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
