apiVersion: v1
kind: ConfigMap
metadata:
  name: mern-config
data:
  PORT: '8080'
  BASE_API_URL: 'api'
  CLIENT_URL: 'http://localhost' # replace with deployed client url
  MONGO_URI: 'mongodb://mongodb-service:27017/mern_ecommerce'
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  JWT_SECRET: KiYlKigmXiVAKiZAI1VZVFVZQGl1eTJ0NDIyOTI4NjQyQUlPVEUmKkAhKTc4NjU= # base64 encoded value
