apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: joker0/mern-ecomm-kub-server:latest # You'll need to update this with your image
          env:
            - name: PORT
              value: '8080'
            - name: BASE_API_URL
              value: 'api'
            - name: MONGO_URI
              value: 'mongodb://mongodb-service:27017/mern_ecommerce'
            - name: JWT_SECRET
              value: 'dOISD78324KJASD67sdsSAIuyiyuas3434'
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              cpu: '100m'
              memory: '256Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
